//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TyranIds.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alerts
    {
        public int AlertId { get; set; }
        public System.Guid DatasourceId { get; set; }
        public string SourceIp { get; set; }
        public Nullable<int> SourcePort { get; set; }
        public string DestinationIp { get; set; }
        public Nullable<int> DestinationPort { get; set; }
        public string Payload { get; set; }
        public byte[] Captured { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
    }
}
